{
 "title": "SmartHome",
 "tags": [
  "smarthome",
  "demo",
  "practicum"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Память Java (занято в куче)",
   "type": "timeseries",
   "description": "Показывает, **сколько памяти реально занято в куче** процесса JVM",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"smarthome\",area=\"heap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Веб-API: запросов в секунду (в среднем)",
   "type": "timeseries",
   "description": "**Сколько HTTP-запросов в секунду** обрабатывает приложение в среднем за последнюю минуту",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"smarthome\"}[1m]))",
     "legendFormat": "Все endpoint вместе"
    }
   ]
  },
  {
   "title": "Веб-API: время ответа, смотрим тяжелый хвост, 95% запросов быстрее",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{job=\"smarthome\"}[5m])) by (le)) * 1000",
     "legendFormat": "Ответ не медленнее этого у 95% запросов"
    }
   ]
  }
 ]
}