apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  weather.lat: "{{ .Values.weather.lat }}"
  weather.lon: "{{ .Values.weather.lon }}"
  weather.interval: "{{ .Values.weather.interval }}"
