apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: smarthome
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: WEATHER_LAT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: weather.lat
            - name: WEATHER_LON
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: weather.lon
            - name: WEATHER_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: weather.interval
            - name: WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: WEATHER_API_KEY
            - name: DB_HOST
              value: "{{ .Release.Name }}-postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "{{ .Values.postgresql.auth.database }}"
            - name: DB_USER
              value: "{{ .Values.postgresql.auth.username }}"
            - name: DB_PASSWORD
              value: "{{ .Values.postgresql.auth.password }}"
            - name: KAFKA_HOST
              value: "{{ .Release.Name }}-kafka"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
